### ISSUE TITLE
Can we use it to send data from Agent to icinga master

### ISSUE THREAD

**Issue by aspryne** [colebrooke/kubernetes-nagios#3]
Hi,
i want to watch my cluster from an Icinga master and not in the other direction =/

Current situation : 
My cluster doesn't have public IP and he is not in the same network from my icinga master (master got public ip and Agent use AWS tools too comunicate with ext.).

Can we run the "script" and command from my cluster directly, to send informations to my icinga master.

I know its complicated to explain but i want know if i can send kube status form my cluster to my icinga master. In this case agent icinga send informations to master icinga but master icinga has nothing to do except display on icingaweb2, because i can't sent check_command to my icinga agent from master.

thanks for your help

**Comment by colebrooke** [comment]
My suggestion would be to create a bastion server on the same network as your kubernetes cluster, and give it an external IP.  Allow your Icinga master to connect to the bastion (whitelist the IP).  Then set up an NRPE agent or similar on the bastion, and set up checks on the basion to check the kubernetes services.  Icinga will essentially call checks defined on the bastion, and give you the status of the kubernetes cluster from there.
It's worth mentioning that these types of checks are not very dynamic or easy to automate.  I would recommend looking at Prometheus, the alert manager plugin, and grafana.  That's what I'm using now for monitoring Kubernetes rather than nagios type check scripts. Although even with these more up to date tools, there are still challenges to make them available from outside of your private network :)

**Comment by aspryne** [comment]
Thank you for your explaination.

I don’t have choice to use icinga2 …. But you right i will use a Bastion, we already have one i must configure him as a « satellite » and my cluster master as a client icinga sync to my satellite.

Thank you for your advices,

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Justin Miller <notifications@github.com>
Envoyé : Thursday, April 18, 2019 2:05:27 PM
À : colebrooke/kubernetes-nagios
Cc : aspryne; Author
Objet : Re: [colebrooke/kubernetes-nagios] Can we use it to send data from Agent to icinga master (#3)


My suggestion would be to create a bastion server on the same network as your kubernetes cluster, and give it an external IP. Allow your Icinga master to connect to the bastion (whitelist the IP). Then set up an NRPE agent or similar on the bastion, and set up checks on the basion to check the kubernetes services. Icinga will essentially call checks defined on the bastion, and give you the status of the kubernetes cluster from there.
It's worth mentioning that these types of checks are not very dynamic or easy to automate. I would recommend looking at Prometheus, the alert manager plugin, and grafana. That's what I'm using now for monitoring Kubernetes rather than nagios type check scripts. Although even with these more up to date tools, there are still challenges to make them available from outside of your private network :)
